### ISSUE TITLE
Specify a licence for the YOS mod.

### ISSUE THREAD

**Issue by WithLithum** [JupiterKasparov/GTAV_YOS#1]
How would you like the code being used? Should it be reusable or people cannot reuse it? Either way, you should make it clear in a `LICENSE` file or in the README so that people knows whether they should be able to reuse the code.

Also, a program is not "open source" unless it is licensed under a license approved by the Open Source Initiative.

**Comment by JupiterKasparov** [comment]
License specified. All code reuse cases, fork scenarios, and abandonware issues are now covered.
