### ISSUE TITLE
Every time a load screen appears (such as when you load online maps in a trainer), YOS resets

### ISSUE THREAD

**Issue by WithLithum** [JupiterKasparov/GTAV_YOS#2]
On each and every load screen appearance, YOS would reset (if without scripts, putting player into the middle of ocean with a seashark and set player model to Michael), even if that load screen is just load online maps in the trainer.

**Excepted behaviour**
The mod should only reset at the first and only loading.

**Actual behaviour**
The mod resets even if you just choose to load online maps in a trainer.

**Comment by JupiterKasparov** [comment]
That is, because YOS actually waits until Prologue hides the loading screen. It detects a new game start upon encountering a loading screen.

I'll be looking into this issue. Maybe it's possible to shutdown the loading screen (SHUTDOWN_LOADING_SCREEN).

Anyway, thanks for your insight.

**Comment by JupiterKasparov** [comment]
Developer oversight fixed! No more loadingscreen-dependent reset!
Mod won't wait for Prologue, and will close initial loading screen on its own (SHUTDOWN_LOADING_SCREEN).

Thanks for your insight!
